// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/index.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryType int32

const (
	EntryType_WRITE  EntryType = 0
	EntryType_DELETE EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "WRITE",
	1: "DELETE",
}
var EntryType_value = map[string]int32{
	"WRITE":  0,
	"DELETE": 1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_index_132053f509dc7fc9, []int{0}
}

type Entry struct {
	Type                 EntryType `protobuf:"varint,1,opt,name=type,enum=pb.EntryType" json:"type,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value                []byte    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Position             int64     `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_132053f509dc7fc9, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_WRITE
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Entry) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type SegmentInfo struct {
	Index                int64    `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentInfo) Reset()         { *m = SegmentInfo{} }
func (m *SegmentInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentInfo) ProtoMessage()    {}
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_132053f509dc7fc9, []int{1}
}
func (m *SegmentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentInfo.Unmarshal(m, b)
}
func (m *SegmentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentInfo.Marshal(b, m, deterministic)
}
func (dst *SegmentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentInfo.Merge(dst, src)
}
func (m *SegmentInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentInfo.Size(m)
}
func (m *SegmentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentInfo proto.InternalMessageInfo

func (m *SegmentInfo) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SegmentInfo) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*SegmentInfo)(nil), "pb.SegmentInfo")
	proto.RegisterEnum("pb.EntryType", EntryType_name, EntryType_value)
}

func init() { proto.RegisterFile("pb/index.proto", fileDescriptor_index_132053f509dc7fc9) }

var fileDescriptor_index_132053f509dc7fc9 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x31, 0x4b, 0xc0, 0x30,
	0x10, 0x85, 0x4d, 0xd3, 0x16, 0x7b, 0x6a, 0x29, 0xc1, 0x21, 0x38, 0xc5, 0x4e, 0xc1, 0xa1, 0x82,
	0xfe, 0x00, 0x17, 0x33, 0x14, 0x9c, 0x62, 0xc1, 0xb9, 0xa9, 0x51, 0x82, 0x9a, 0x1c, 0x35, 0x8a,
	0xf9, 0xf7, 0xd2, 0x14, 0xba, 0xdd, 0xc7, 0x83, 0xf7, 0xbe, 0x83, 0x16, 0xcd, 0xad, 0xf3, 0xaf,
	0xf6, 0x6f, 0xc0, 0x35, 0xc4, 0xc0, 0x0a, 0x34, 0xbd, 0x87, 0x4a, 0xf9, 0xb8, 0x26, 0x76, 0x0d,
	0x65, 0x4c, 0x68, 0x39, 0x11, 0x44, 0xb6, 0x77, 0x17, 0x03, 0x9a, 0x21, 0x07, 0x53, 0x42, 0xab,
	0x73, 0xc4, 0x3a, 0xa0, 0x1f, 0x36, 0xf1, 0x42, 0x10, 0xd9, 0xe8, 0xed, 0x64, 0x97, 0x50, 0xfd,
	0xce, 0x9f, 0x3f, 0x96, 0x53, 0x41, 0xe4, 0xb9, 0xde, 0x81, 0x5d, 0xc1, 0x29, 0x86, 0x6f, 0x17,
	0x5d, 0xf0, 0xbc, 0x14, 0x44, 0x52, 0x7d, 0x70, 0xff, 0x00, 0x67, 0xcf, 0xf6, 0xfd, 0xcb, 0xfa,
	0x38, 0xfa, 0xb7, 0xb0, 0x15, 0x64, 0xa3, 0x3c, 0x4b, 0xf5, 0x0e, 0x5b, 0xc1, 0x32, 0xe3, 0xbc,
	0xb8, 0xb8, 0xaf, 0x51, 0x7d, 0xf0, 0x4d, 0x0f, 0xcd, 0xe1, 0xc5, 0x1a, 0xa8, 0x5e, 0xf4, 0x38,
	0xa9, 0xee, 0x84, 0x01, 0xd4, 0x8f, 0xea, 0x49, 0x4d, 0xaa, 0x23, 0xa6, 0xce, 0xff, 0xdd, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xea, 0xe8, 0xb2, 0xf9, 0xf1, 0x00, 0x00, 0x00,
}
