// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/index.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryType int32

const (
	EntryType_WRITE  EntryType = 0
	EntryType_DELETE EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "WRITE",
	1: "DELETE",
}
var EntryType_value = map[string]int32{
	"WRITE":  0,
	"DELETE": 1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_index_0f0c9f9b32191704, []int{0}
}

type Entry struct {
	Type                 EntryType `protobuf:"varint,1,opt,name=type,enum=pb.EntryType" json:"type,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value                []byte    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_0f0c9f9b32191704, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_WRITE
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterEnum("pb.EntryType", EntryType_name, EntryType_value)
}

func init() { proto.RegisterFile("pb/index.proto", fileDescriptor_index_0f0c9f9b32191704) }

var fileDescriptor_index_0f0c9f9b32191704 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0xd2, 0xcf,
	0xcc, 0x4b, 0x49, 0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a,
	0xe2, 0x62, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x52, 0xe4, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd5, 0x2b, 0x48, 0xd2, 0x03, 0x4b, 0x84, 0x54, 0x16,
	0xa4, 0x06, 0x81, 0xa5, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x4b, 0x89, 0x8b, 0x13, 0xae, 0x55, 0x88, 0x93, 0x8b, 0x35,
	0x3c, 0xc8, 0x33, 0xc4, 0x55, 0x80, 0x41, 0x88, 0x8b, 0x8b, 0xcd, 0xc5, 0xd5, 0xc7, 0x35, 0xc4,
	0x55, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x04, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x12,
	0xd5, 0x48, 0x94, 0x00, 0x00, 0x00,
}
