// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/hash/pb/index.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryType int32

const (
	EntryType_WRITE  EntryType = 0
	EntryType_DELETE EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "WRITE",
	1: "DELETE",
}
var EntryType_value = map[string]int32{
	"WRITE":  0,
	"DELETE": 1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_index_cb6198551122180a, []int{0}
}

type LogEntry struct {
	Type                 EntryType `protobuf:"varint,1,opt,name=type,enum=pb.EntryType" json:"type,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value                []byte    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_cb6198551122180a, []int{0}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (dst *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(dst, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_WRITE
}

func (m *LogEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LogEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "pb.LogEntry")
	proto.RegisterEnum("pb.EntryType", EntryType_name, EntryType_value)
}

func init() { proto.RegisterFile("storage/hash/pb/index.proto", fileDescriptor_index_cb6198551122180a) }

var fileDescriptor_index_cb6198551122180a = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4c, 0x4f, 0xd5, 0xcf, 0x48, 0x2c, 0xce, 0xd0, 0x2f, 0x48, 0xd2, 0xcf, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe5, 0xe2, 0xf0,
	0xc9, 0x4f, 0x77, 0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x52, 0xe4, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd5, 0x2b, 0x48, 0xd2, 0x03, 0x4b, 0x84, 0x54, 0x16,
	0xa4, 0x06, 0x81, 0xa5, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x4b, 0x89, 0x8b, 0x13, 0xae, 0x55, 0x88, 0x93, 0x8b, 0x35,
	0x3c, 0xc8, 0x33, 0xc4, 0x55, 0x80, 0x41, 0x88, 0x8b, 0x8b, 0xcd, 0xc5, 0xd5, 0xc7, 0x35, 0xc4,
	0x55, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x0a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xfa,
	0x7a, 0xcd, 0xa4, 0x00, 0x00, 0x00,
}
